using System.Text.Json.Serialization;

namespace NEMSweep.Contracts;

/// <summary>
/// Index for one sweep (<c>sweeps/{sweepId}/index.json</c>): the axis it varies, the scope its
/// results share (if any), how it was produced, and one entry per point. Per-point detail
/// artifacts are reachable from here via <see cref="SweepIndexPointDTO.DetailPath"/>; this index is
/// enough on its own to draw the sweep's summary chart and table.
/// </summary>
/// <param name="SchemaVersion">Schema version of this artifact.</param>
/// <param name="SweepId">Identifier for the sweep, unique among published sweeps.</param>
/// <param name="Name">Human-readable name of the sweep.</param>
/// <param name="Axis">What the sweep varies and how its points are labelled on a chart's x-axis.</param>
/// <param name="Scope">
/// Region, period, resolution and weather basis every point's results share, or null when the
/// points do not all share one.
/// </param>
/// <param name="Provenance">How this sweep was produced, and from which inputs.</param>
/// <param name="Points">One entry per point the sweep definition declared, in definition order.</param>
public sealed record SweepIndexDTO(
    int SchemaVersion,
    string SweepId,
    string Name,
    SweepAxisDTO Axis,
    SweepScopeDTO? Scope,
    SweepProvenanceDTO Provenance,
    SweepIndexPointDTO[] Points);

/// <summary>
/// What a sweep varies. A display label and unit only: the actual parameter change for each point
/// lives in that point's own overrides, not here. <see cref="SweepIndexPointDTO.AxisValue"/> is the
/// value to plot against this axis; it does not by itself describe what changed.
/// </summary>
/// <param name="Label">Display label for the axis (for example "Data centre nameplate added").</param>
/// <param name="Unit">Unit the axis values are expressed in (for example "MW").</param>
public sealed record SweepAxisDTO(
    string Label,
    string Unit);

/// <summary>
/// What the sweep's results describe: which regions, over which period, at which resolution, and
/// against which weather. Null when the sweep's points do not share one period and resolution,
/// because a heterogeneous sweep has no single scope and stating one would be false.
/// </summary>
/// <param name="RegionIds">Every region covered by any point in the sweep, sorted ordinally.</param>
/// <param name="PeriodStart">Inclusive start of the dispatch period, in NEM market time (UTC+10).</param>
/// <param name="PeriodEnd">Exclusive end of the dispatch period, in NEM market time (UTC+10).</param>
/// <param name="Resolution">Duration of one dispatch interval, shared by every point's results.</param>
/// <param name="WeatherBasis">Weather basis every point's results were dispatched against.</param>
public sealed record SweepScopeDTO(
    string[] RegionIds,
    DateTimeOffset PeriodStart,
    DateTimeOffset PeriodEnd,
    TimeSpan Resolution,
    WeatherBasisDTO WeatherBasis);

/// <summary>
/// Reproducibility record for a sweep: the code that produced it, and the exact inputs it read. The
/// same commit run against the same inputs reproduces identical artifacts; either changing makes no
/// such guarantee.
/// </summary>
/// <param name="GitCommitSha">Git commit the model was built at, stamped into the binary by its build.</param>
/// <param name="WorkingTreeDirty">
/// True when the run was made from a checkout standing on <see cref="GitCommitSha"/> that had
/// uncommitted changes, so the commit alone does not fully pin the code that produced this sweep.
/// False when the run was made from a binary built elsewhere, where the source tree is not present
/// to inspect.
/// </param>
/// <param name="ResolvedDefinitionSha256">
/// SHA-256, in lowercase hex, of the sweep definition after resolution (with defaults applied and
/// paths normalised), not of the definition file's raw bytes.
/// </param>
/// <param name="InputFiles">
/// Every genuine input file the sweep read: the sweep definition, the baseline scenario config,
/// and each point's demand and weather artifacts. Per-point configs generated by the run are not
/// listed here, because they are outputs, reachable from each point's own
/// <see cref="SweepIndexPointDTO.ConfigPath"/>.
/// </param>
/// <param name="SchemaVersions">
/// Schema version of each artifact kind this sweep run reads or writes, keyed by kind name.
/// </param>
/// <param name="TotalDurationMs">Wall-clock time the whole sweep run took, in milliseconds, when recorded.</param>
public sealed record SweepProvenanceDTO(
    string GitCommitSha,
    bool WorkingTreeDirty,
    string ResolvedDefinitionSha256,
    SweepInputFileDTO[] InputFiles,
    Dictionary<string, int> SchemaVersions,
    double? TotalDurationMs = null);

/// <summary>One genuine input file a sweep run read, identified by content.</summary>
/// <param name="Path">Path to the file, relative to the solution root, with forward slashes.</param>
/// <param name="Purpose">
/// What role the file played (for example <c>sweep-definition</c>, <c>baseline-scenario-config</c>,
/// <c>demand-data</c>, <c>weather-data</c>).
/// </param>
/// <param name="Sha256">SHA-256, in lowercase hex, of the file's exact bytes as read.</param>
public sealed record SweepInputFileDTO(
    string Path,
    string Purpose,
    string Sha256);

/// <summary>
/// One point of a sweep: its axis position, whether it succeeded, and, for a succeeded point,
/// the results copied up from its own detail artifact for the index to serve without a second
/// fetch. Region-scoped fields are populated only for a multi-region sweep; a single-region sweep
/// carries its figures in the top-level fields instead.
/// </summary>
/// <param name="PointId">Identifier for the point, unique within the sweep.</param>
/// <param name="Label">Display label for the point (for example "+500 MW").</param>
/// <param name="AxisValue">
/// Value to plot against <see cref="SweepAxisDTO"/>. Display only: it does not itself carry the
/// parameter change the point applied. That lives in the point's own overrides, which this index
/// does not repeat.
/// </param>
/// <param name="Status">Whether the point succeeded or failed.</param>
/// <param name="DetailPath">
/// Path to the point's whole-system detail artifact, relative to the sweep directory, when the
/// point succeeded.
/// </param>
/// <param name="ConfigPath">
/// Path to the point's resolved scenario config as emitted by the run, relative to the sweep
/// directory. Present whether or not the point succeeded.
/// </param>
/// <param name="Scalars">Whole-system scalar results copied from the point's detail artifact, when it succeeded.</param>
/// <param name="Reliability">Whole-system reliability basis copied from the point's detail artifact, when it succeeded.</param>
/// <param name="StorageSizing">Whole-system storage sizing outcome copied from the point's detail artifact, when it succeeded.</param>
/// <param name="IntervalPointers">Whole-system interval pointers copied from the point's detail artifact, when it succeeded.</param>
/// <param name="Failure">Why the point failed, when it did not succeed.</param>
/// <param name="RegionScalars">Per-region scalar results, for a multi-region sweep, when the point succeeded.</param>
/// <param name="RegionDetails">Per-region detail artifact paths, for a multi-region sweep, when the point succeeded.</param>
/// <param name="OverviewPath">
/// Path to the point's compact whole-system overview artifact, relative to the sweep directory,
/// when the point succeeded.
/// </param>
/// <param name="DurationMs">Wall-clock time this point's run took, in milliseconds, when recorded.</param>
public sealed record SweepIndexPointDTO(
    string PointId,
    string Label,
    double AxisValue,
    SweepPointStatus Status,
    string? DetailPath,
    string ConfigPath,
    SweepPointScalarResultsDTO? Scalars,
    ReliabilityBasisDTO? Reliability,
    StorageSizingOutcomeDTO? StorageSizing,
    IntervalPointersDTO? IntervalPointers,
    SweepPointFailureDTO? Failure,
    SweepPointRegionScalarsDTO[]? RegionScalars = null,
    SweepPointRegionDetailDTO[]? RegionDetails = null,
    string? OverviewPath = null,
    double? DurationMs = null);

/// <summary>Scalar results for one region of a succeeded, multi-region sweep point.</summary>
/// <param name="RegionId">NEM region these scalars describe (for example <c>NSW1</c>).</param>
/// <param name="Scalars">This region's scalar results, copied from its own detail artifact.</param>
public sealed record SweepPointRegionScalarsDTO(
    string RegionId,
    SweepPointScalarResultsDTO Scalars);

/// <summary>Detail artifact locations for one region of a succeeded, multi-region sweep point.</summary>
/// <param name="RegionId">NEM region these paths describe (for example <c>NSW1</c>).</param>
/// <param name="DetailPath">Path to this region's detail artifact, relative to the sweep directory.</param>
/// <param name="OverviewPath">Path to this region's compact overview artifact, relative to the sweep directory, when published.</param>
public sealed record SweepPointRegionDetailDTO(
    string RegionId,
    string DetailPath,
    string? OverviewPath = null);

/// <summary>Closed set of sweep point outcomes, so both sides fail at the boundary.</summary>
[JsonConverter(typeof(JsonStringEnumConverter<SweepPointStatus>))]
public enum SweepPointStatus
{
    /// <summary>The point ran to completion and its results were published.</summary>
    [JsonStringEnumMemberName("succeeded")]
    Succeeded,

    /// <summary>The point did not complete; see the sibling <see cref="SweepPointFailureDTO"/> for why.</summary>
    [JsonStringEnumMemberName("failed")]
    Failed,
}

/// <summary>
/// Why a point did not produce results. <see cref="Stage"/> and <see cref="Code"/> are for
/// grouping and branching; <see cref="Message"/> is for reading.
/// </summary>
/// <param name="Stage">Stage of the run the failure occurred in.</param>
/// <param name="Code">Short, stable code identifying the failure, for grouping without matching on message text.</param>
/// <param name="Message">Human-readable description of the failure.</param>
public sealed record SweepPointFailureDTO(
    SweepFailureStage Stage,
    string Code,
    string Message);

/// <summary>Stage of the run a sweep point failed in.</summary>
[JsonConverter(typeof(JsonStringEnumConverter<SweepFailureStage>))]
public enum SweepFailureStage
{
    /// <summary>The point's configuration or an input artifact could not be read or validated.</summary>
    [JsonStringEnumMemberName("input")]
    Input,

    /// <summary>Dispatch could not be simulated.</summary>
    [JsonStringEnumMemberName("dispatch")]
    Dispatch,

    /// <summary>The storage sizing loop did not reach the reliability target.</summary>
    [JsonStringEnumMemberName("sizing")]
    Sizing,

    /// <summary>System costs could not be calculated.</summary>
    [JsonStringEnumMemberName("costing")]
    Costing,

    /// <summary>The point ran but its artifacts could not be written.</summary>
    [JsonStringEnumMemberName("export")]
    Export,

    /// <summary>The failure could not be attributed to a stage.</summary>
    [JsonStringEnumMemberName("unknown")]
    Unknown,
}

/// <summary>
/// Per-point figures carried by the index so an all-runs table costs one fetch. Every field here
/// is a copy of a figure in the point's own detail artifact; the display label and unit for each
/// come from <see cref="SweepScalarCatalog"/>.
/// </summary>
/// <param name="SlcoeAudPerMwh">System levelised cost of energy, in AUD per MWh served.</param>
/// <param name="GenerationSlcoeAudPerMwh">Generation component of levelised cost, in AUD per MWh served.</param>
/// <param name="StorageSlcoeAudPerMwh">Storage component of levelised cost, in AUD per MWh served.</param>
/// <param name="DemandMwh">Total demand energy over the dispatch period, in MWh.</param>
/// <param name="EnergyServedMwh">Demand energy actually served, in MWh (demand less unserved energy).</param>
/// <param name="DeliveredGenerationMwh">Generation energy net of curtailment and storage charging, in MWh. Not the same as energy served.</param>
/// <param name="AchievedRenewableShareGridScale">
/// Renewable share of delivered generation counting only grid-scale generation, as a fraction in
/// [0, 1]; null when it could not be computed.
/// </param>
/// <param name="AchievedRenewableShareNative">
/// Renewable share of delivered generation counting native (behind-the-meter) generation as well,
/// as a fraction in [0, 1]; null when it could not be computed.
/// </param>
/// <param name="StoragePowerMw">Installed storage power capacity, in MW.</param>
/// <param name="StorageEnergyMwh">Installed storage energy capacity, in MWh.</param>
/// <param name="UnservedEnergyMwh">Energy that could not be served over the dispatch period, in MWh.</param>
/// <param name="UnservedEnergyPercentageOfDemand">Unserved energy as a percentage of demand energy.</param>
/// <param name="UnservedHours">Count of intervals with any unserved energy.</param>
/// <param name="HoursServedFraction">Fraction of intervals with no unserved energy, in [0, 1].</param>
/// <param name="PeakUnservedPowerMw">Largest unserved power in any single interval, in MW.</param>
/// <param name="CurtailedEnergyMwh">Generation energy curtailed rather than delivered, in MWh.</param>
/// <param name="TransmissionSlcotAudPerMwh">Transmission component of levelised cost, in AUD per MWh served.</param>
/// <param name="TransmissionCostStatus">Whether the transmission cost figure could be calculated for this point.</param>
/// <param name="NetImportedEnergyMwh">
/// Net energy imported across interconnectors over the dispatch period, in MWh; negative when the
/// point was a net exporter.
/// </param>
public sealed record SweepPointScalarResultsDTO(
    // Money stays decimal deliberately: these are currency values, not measurements.
    decimal SlcoeAudPerMwh,
    decimal GenerationSlcoeAudPerMwh,
    decimal StorageSlcoeAudPerMwh,
    double DemandMwh,
    double EnergyServedMwh,
    double DeliveredGenerationMwh,
    double? AchievedRenewableShareGridScale,
    double? AchievedRenewableShareNative,
    double StoragePowerMw,
    double StorageEnergyMwh,
    double UnservedEnergyMwh,
    double UnservedEnergyPercentageOfDemand,
    int UnservedHours,
    double HoursServedFraction,
    double PeakUnservedPowerMw,
    double CurtailedEnergyMwh,
    [property: JsonRequired] decimal TransmissionSlcotAudPerMwh,
    [property: JsonRequired] TransmissionCostStatus TransmissionCostStatus,
    [property: JsonRequired] double NetImportedEnergyMwh);

/// <summary>
/// A base-demand or similar series externalised to <c>series/base-demand-{sha256}.json</c> and
/// referenced by path, so points sharing an identical profile share one file instead of each
/// repeating it. Content-addressed by the SHA-256 of this artifact's own serialised bytes.
/// </summary>
/// <param name="SchemaVersion">Schema version of this artifact.</param>
/// <param name="Start">Timestamp of the first value, in NEM market time (UTC+10).</param>
/// <param name="Resolution">Duration of one interval.</param>
/// <param name="ValuesMw">
/// Interval-average power for each interval, in MW, starting at <see cref="Start"/>. Integrates to
/// MWh over an interval's duration.
/// </param>
public sealed record RegularSeriesDTO(
    int SchemaVersion,
    DateTimeOffset Start,
    TimeSpan Resolution,
    double[] ValuesMw);
